CREATE TABLE IF NOT EXISTS jclg_stream (
    stream_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_code VARCHAR(20) NOT NULL UNIQUE,
    stream_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS jclg_group (
    group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR(20) NOT NULL UNIQUE,
    group_name VARCHAR(100) NOT NULL,
    stream_id INTEGER NOT NULL REFERENCES jclg_stream(stream_id)
);

ALTER TABLE IF EXISTS jclg_student ADD COLUMN IF NOT EXISTS admission_no VARCHAR(50);
ALTER TABLE IF EXISTS jclg_student ADD COLUMN IF NOT EXISTS name VARCHAR(150);
ALTER TABLE IF EXISTS jclg_student ADD COLUMN IF NOT EXISTS student_code VARCHAR(50);
ALTER TABLE IF EXISTS jclg_student ADD COLUMN IF NOT EXISTS stream_id INTEGER;
ALTER TABLE IF EXISTS jclg_student ADD COLUMN IF NOT EXISTS group_id INTEGER;

CREATE TABLE IF NOT EXISTS jclg_student (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code VARCHAR(50) NOT NULL UNIQUE,
    admission_no VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    class_name VARCHAR(50) NOT NULL,
    section VARCHAR(30) NOT NULL,
    stream_id INTEGER NOT NULL REFERENCES jclg_stream(stream_id),
    group_id INTEGER NOT NULL REFERENCES jclg_group(group_id)
);

CREATE TABLE IF NOT EXISTS jclg_parent (
    parent_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    contact VARCHAR(30) NOT NULL,
    relation VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS jclg_student_parent (
    student_id INTEGER NOT NULL REFERENCES jclg_student(student_id) ON DELETE CASCADE,
    parent_id INTEGER NOT NULL REFERENCES jclg_parent(parent_id) ON DELETE CASCADE,
    PRIMARY KEY (student_id, parent_id)
);

ALTER TABLE IF EXISTS jclg_subject ADD COLUMN IF NOT EXISTS stream_id INTEGER;

CREATE TABLE IF NOT EXISTS jclg_subject (
    subject_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code VARCHAR(20) NOT NULL UNIQUE,
    subject_name VARCHAR(100) NOT NULL,
    stream_id INTEGER NOT NULL REFERENCES jclg_stream(stream_id),
    UNIQUE (subject_name, stream_id)
);

CREATE TABLE IF NOT EXISTS jclg_exam (
    exam_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_name VARCHAR(100) NOT NULL,
    exam_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS jclg_attendance (
    attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES jclg_student(student_id) ON DELETE CASCADE,
    attendance_date DATE NOT NULL,
    status BOOLEAN NOT NULL,
    assignments_completed INTEGER NOT NULL DEFAULT 0,
    participation_score NUMERIC(5,2) NOT NULL DEFAULT 0,
    engagement_status VARCHAR(30) NOT NULL DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS jclg_marks (
    mark_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES jclg_student(student_id) ON DELETE CASCADE,
    subject_id INTEGER NOT NULL REFERENCES jclg_subject(subject_id),
    exam_id INTEGER NOT NULL REFERENCES jclg_exam(exam_id),
    marks_obtained NUMERIC(6,2) NOT NULL CHECK (marks_obtained >= 0),
    total_marks NUMERIC(6,2) NOT NULL CHECK (total_marks > 0),
    exam_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Published'
);

CREATE TABLE IF NOT EXISTS jclg_result (
    result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES jclg_student(student_id) ON DELETE CASCADE,
    exam_id INTEGER NOT NULL REFERENCES jclg_exam(exam_id),
    total_marks NUMERIC(8,2) NOT NULL,
    percentage NUMERIC(5,2) NOT NULL CHECK (percentage BETWEEN 0 AND 100),
    grade VARCHAR(10) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Published'
);

ALTER TABLE IF EXISTS jclg_result ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'Published';

CREATE TABLE IF NOT EXISTS jclg_ai_usage (
    usage_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES jclg_student(student_id) ON DELETE CASCADE,
    module_name VARCHAR(80) NOT NULL,
    tokens_used INTEGER NOT NULL CHECK (tokens_used >= 0),
    used_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jclg_ai_insight (
    insight_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES jclg_student(student_id) ON DELETE CASCADE,
    stream_id INTEGER NOT NULL REFERENCES jclg_stream(stream_id),
    analysis_type VARCHAR(80) NOT NULL,
    risk_level VARCHAR(20) NOT NULL CHECK (LOWER(risk_level) IN ('low', 'moderate', 'high')),
    recommendation TEXT NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'jclg_student_stream_fk'
    ) THEN
        ALTER TABLE jclg_student
            ADD CONSTRAINT jclg_student_stream_fk FOREIGN KEY (stream_id) REFERENCES jclg_stream(stream_id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'jclg_student_group_fk'
    ) THEN
        ALTER TABLE jclg_student
            ADD CONSTRAINT jclg_student_group_fk FOREIGN KEY (group_id) REFERENCES jclg_group(group_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS jclg_attendance_student_idx ON jclg_attendance(student_id);
CREATE INDEX IF NOT EXISTS jclg_marks_student_idx ON jclg_marks(student_id);
CREATE INDEX IF NOT EXISTS jclg_result_student_idx ON jclg_result(student_id);
CREATE INDEX IF NOT EXISTS jclg_ai_usage_student_idx ON jclg_ai_usage(student_id);
CREATE INDEX IF NOT EXISTS jclg_ai_insight_student_idx ON jclg_ai_insight(student_id);
